### ISSUE TITLE
atc_classifications split into two fields

### ISSUE THREAD

**Issue by junjun-zhang** [docking-org/OICR-ZINC#3]
Before moving to GitHub, there is one field for atc code:

> ```
>    "atc_classifications": [
>       {
>            "level4": "L01AA",
>            "level4_description": "Nitrogen mustard analogues",
>            "level5": "L01AA07",
>            "who_name": "trofosfamide"
>        }
>    ],
> ```

What's in the git repo now:

> ```
>    "atc_codes": [
>        {
>            "code": "L01AA",
>            "description": "Nitrogen mustard analogues"
>        }
>    ],
>    "atc_level5_codes": [
>        "L01AA07"
>    ],
> ```

Can we merge these two into one field as before?

**Comment by jir322** [comment]
Yes, sorry this got bungled as we moved into github. We'll push to github
later today and let you know.

**Comment by jir322** [comment]
FIXED

**Comment by teaguesterling** [comment]
Solved by 5b5bae6849d1ac58b799219fccb461779e4300ae for the record
